title: muOS
description: Custom Firmware (CFW) primarily for handheld devices. Configurable, themeable, friendly, easy-to-use.
theme: just-the-docs

url: https://muos.dev

color_scheme: muos

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
